// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfShqOSy_cE9r6sMHNEGPzneGs03j_UcE',
    appId: '1:768073379160:web:c40ece2378a1bb24d9092d',
    messagingSenderId: '768073379160',
    projectId: 'codealpha-language-learning',
    authDomain: 'codealpha-language-learning.firebaseapp.com',
    storageBucket: 'codealpha-language-learning.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUgomi8uch1FEcJ7ons_1Yozm-0NAxGOI',
    appId: '1:768073379160:ios:16ce98c75c456c75d9092d',
    messagingSenderId: '768073379160',
    projectId: 'codealpha-language-learning',
    storageBucket: 'codealpha-language-learning.firebasestorage.app',
    iosBundleId: 'com.example.codealphaLanguageLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUgomi8uch1FEcJ7ons_1Yozm-0NAxGOI',
    appId: '1:768073379160:ios:16ce98c75c456c75d9092d',
    messagingSenderId: '768073379160',
    projectId: 'codealpha-language-learning',
    storageBucket: 'codealpha-language-learning.firebasestorage.app',
    iosBundleId: 'com.example.codealphaLanguageLearning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfShqOSy_cE9r6sMHNEGPzneGs03j_UcE',
    appId: '1:768073379160:web:146849ce0adbda78d9092d',
    messagingSenderId: '768073379160',
    projectId: 'codealpha-language-learning',
    authDomain: 'codealpha-language-learning.firebaseapp.com',
    storageBucket: 'codealpha-language-learning.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzVrk8Sii4qRPcNJf-GiIgiTjO56C2pFI',
    appId: '1:768073379160:android:f1eb61700f715311d9092d',
    messagingSenderId: '768073379160',
    projectId: 'codealpha-language-learning',
    storageBucket: 'codealpha-language-learning.firebasestorage.app',
  );
}
